### ISSUE TITLE
Good demo.

### ISSUE THREAD

**Issue by dwjohnston** [t7yang/ts-yarn-workspace-demo#1]
Nice and clean. 

I don't like how you have to copy-paste a tsconfig into each package, but it seems that this is the only way to do it.

**Comment by t7yang** [comment]
No, the share part is place on the root `tsconfig.json` and each workspace's `tsconfig.json` represent their own TypeScript config, this is the way how you work with workspace style monorepo. (You can reference to the famous [Nx](https://github.com/nrwl/nx) project).
